// Autogenerated by: MongoDB

let database = {
    host: 'localhost',
    name: 'MaryJane',
    clusters : {
        collections: {
            seven_letter_words: [
                'pinewood',
                'jailbird',
                'awkwardly',
                'divebomb',
            ]
        }
    }
};

module.exports = database;
